# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- {name: 'Google Search Project',     url: 'project0/index.html'}
- {name: 'Pet Pals Playdate Website',   url: 'https://github.com/vandsama/tech.elevator.final.capstone.pet.pals'}
# - {name: 'Education',  url: 'education'}
# - {name: 'Experience', url: 'experience'}
# - {name: 'About',      url: 'about'}
# - {name: 'Contact',    url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
 social:
 - {icon: 'linkedin', link:    'https://www.linkedin.com/in/s-vanderburgh/'}
# - {icon: 'twitter', link:    'https://twitter.com/paululele'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {icon: 'instagram', link:  'https://instagram.com/paululele'}
# - {icon: 'envelope', link:   'mailto:vandsama@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
